version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    networks:
      - laravel-net

  webserver:
    image: nginx:stable
    container_name: nginx-laravel
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
